# Generated by Django 4.2.19 on 2025-03-04 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='age',
        ),
        migrations.RemoveField(
            model_name='member',
            name='notes',
        ),
        migrations.AddField(
            model_name='member',
            name='activity_type',
            field=models.CharField(choices=[('culture', 'Culture (céréales, légumes, etc.)'), ('elevage', 'Élevage (bovins, ovins, volailles…)'), ('apiculture', 'Apiculture (élevage d’abeilles)'), ('maraichage', 'Maraîchage (légumes et plantes comestibles)'), ('arboriculture', 'Arboriculture (arbres fruitiers, oliviers, etc.)'), ('autre', 'Autre')], default='culture', max_length=20),
        ),
        migrations.AddField(
            model_name='member',
            name='email',
            field=models.EmailField(default='name@gmail.com', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='member',
            name='motivation',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='telephone',
            field=models.CharField(default='0000000000', max_length=25),
        ),
    ]
