# Generated by Django 4.2.19 on 2025-03-10 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='motivation',
        ),
    ]
