# Generated by Django 4.2.19 on 2025-03-11 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_memberpayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberpayment',
            name='member',
        ),
        migrations.AddField(
            model_name='memberpayment',
            name='name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
