# Generated by Django 4.2.19 on 2025-03-11 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_memberpayment_member_memberpayment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberpayment',
            name='phone',
            field=models.CharField(default='0000000000', max_length=25),
        ),
    ]
